url: "https://creativeforum.yale.edu"
title: "Variantes"
future: true
baseurl: "/variantes"

owner: Yale Department of Spanish & Portuguese
email: ana.fernandez-blazquez@yale.edu

collections:
  num0:
    output: true
  num1:
    output: true

sass:
  load_paths:
    - _sass

webrick:
  headers:
    Cache-Control: no-store, must-revalidate
    Pragma: no-cache
    Expires: 0
